In [1]:
from pyspark.sql import SparkSession
from itertools import product

from main import main
from query1 import *
from query2 import *
from query3 import *
from query4 import *
from load import *

In [5]:
main()

Initializing spark session
Loading crime data dataframe
+--------------+------+
|Vict Age Group| count|
+--------------+------+
|         25-64|115298|
|         18-24| 32197|
|           <18| 15321|
|           >64|  5676|
+--------------+------+

Execution time for query1_dataframe: 1.5002 seconds
+--------------+------+
|Vict Age Group| count|
+--------------+------+
|         25-64|115298|
|         18-24| 32197|
|           <18| 15321|
|           >64|  5676|
+--------------+------+

Execution time for query1_rdd: 13.5813 seconds
Running query 2 RDD
+----+-----------+--------------------+---+
|year|   precinct|    closed_case_rate|  #|
+----+-----------+--------------------+---+
|2010|    Rampart| 0.32847134489491214|  1|
|2010|    Olympic|  0.3151528982199909|  2|
|2010|     Harbor|  0.2936028339237341|  3|
|2010|West Valley| 0.25979070018340705|  4|
|2010| Hollenbeck|  0.2520928976505536|  5|
|2010|  Northeast|  0.2470599303791514|  6|
|2010|  Southeast| 0.24034296028880867|  7|
|2010|     Newton| 0.23422342234223423|  8|
|2010|   Van Nuys| 0.21825750817722273|  9|
|2010|N Hollywood| 0.20818301803783545| 10|
|2010|  Southwest|  0.1888270610631132| 11|
|2010|  Hollywood|  0.1694896851248643| 12|
|2010|    Central| 0.16946543520850826| 13|
|2010|   Wilshire| 0.15355484974346445| 14|
|2010|    Pacific| 0.09528531506355359| 15|
|2010|    Topanga| 0.06825284806936183| 16|
|2010|   Foothill|0.056363636363636366| 17|
|2010|    Mission|0.053777693618632834| 18|
|2010|    West LA| 0.04719512195121951| 19|
|2010| Devonshire|0.024433793816370643| 20|
+----+-----------+--------------------+---+
only showing top 20 rows

Execution time for query2_rdd: 12.5402 seconds
Running query 2 SQL
+----+-----------+--------------------+---+
|year|   precinct|    closed_case_rate|  #|
+----+-----------+--------------------+---+
|2010|    Rampart| 0.32847134489491214|  1|
|2010|    Olympic|  0.3151528982199909|  2|
|2010|     Harbor|  0.2936028339237341|  3|
|2010|West Valley| 0.25979070018340705|  4|
|2010| Hollenbeck|  0.2520928976505536|  5|
|2010|  Northeast|  0.2470599303791514|  6|
|2010|  Southeast| 0.24034296028880867|  7|
|2010|     Newton| 0.23422342234223423|  8|
|2010|   Van Nuys| 0.21825750817722273|  9|
|2010|N Hollywood| 0.20818301803783545| 10|
|2010|  Southwest|  0.1888270610631132| 11|
|2010|  Hollywood|  0.1694896851248643| 12|
|2010|    Central| 0.16946543520850826| 13|
|2010|   Wilshire| 0.15355484974346445| 14|
|2010|    Pacific| 0.09528531506355359| 15|
|2010|    Topanga| 0.06825284806936183| 16|
|2010|   Foothill|0.056363636363636366| 17|
|2010|    Mission|0.053777693618632834| 18|
|2010|    West LA| 0.04719512195121951| 19|
|2010| Devonshire|0.024433793816370643| 20|
+----+-----------+--------------------+---+
only showing top 20 rows

Execution time for query2_sql: 1.4179 seconds
Saving crime data to a single parquet file
Loading crime data from single parquet file
Running query 2 RDD again with the dataframe being loaded from a single parquet file
+----+-----------+--------------------+---+
|year|   precinct|    closed_case_rate|  #|
+----+-----------+--------------------+---+
|2010|    Rampart| 0.32847134489491214|  1|
|2010|    Olympic|  0.3151528982199909|  2|
|2010|     Harbor|  0.2936028339237341|  3|
|2010|West Valley| 0.25979070018340705|  4|
|2010| Hollenbeck|  0.2520928976505536|  5|
|2010|  Northeast|  0.2470599303791514|  6|
|2010|  Southeast| 0.24034296028880867|  7|
|2010|     Newton| 0.23422342234223423|  8|
|2010|   Van Nuys| 0.21825750817722273|  9|
|2010|N Hollywood| 0.20818301803783545| 10|
|2010|  Southwest|  0.1888270610631132| 11|
|2010|  Hollywood|  0.1694896851248643| 12|
|2010|    Central| 0.16946543520850826| 13|
|2010|   Wilshire| 0.15355484974346445| 14|
|2010|    Pacific| 0.09528531506355359| 15|
|2010|    Topanga| 0.06825284806936183| 16|
|2010|   Foothill|0.056363636363636366| 17|
|2010|    Mission|0.053777693618632834| 18|
|2010|    West LA| 0.04719512195121951| 19|
|2010| Devonshire|0.024433793816370643| 20|
+----+-----------+--------------------+---+
only showing top 20 rows

Execution time for query2_rdd: 19.5356 seconds
Loading income dataframe
Loading census blocks dataframe

TypeError: 'JavaPackage' object is not callable